---
Name: mysite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'foundation'

Member:
  extensions:
    - MemberExtend

Article:
  extensions:
    - Linkable
    
Project:
  extensions:
    - Linkable

Image:
  extensions:
    - GrayscaleDecorator

SiteConfig:
  extensions:
    - SiteConfigDecorator
    
Director:
  environment_type: 'dev'