---
Name: mysite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs

Member:
  extensions:
    - MemberExtend

Article:
  extensions:
    - Linkable

ArticleImage:
  extensions:
    - SortableDataObject
    
Project:
  extensions:
    - Linkable

Image:
  extensions:
    - GrayscaleDecorator

SiteConfig:
  extensions:
    - SiteConfigDecorator
    
Director:
  environment_type: 'dev'

Profile:
  extensions:
    - SortableDataObject

Quote:
  extensions:
    - SortableDataObject

AssetAdmin:
  treats_subsite_0_as_global: false

DateField:
  default_config:
    showcalendar: true
    dmyfields: true;